### ISSUE TITLE
有哪些依赖？

### ISSUE THREAD

**Issue by jiajunhuang** [wiiiky/layoutcode#1]
除了beautifulsoup4还有哪些依赖？

``` bash
$ ./layout.py -i test/base.xml 
Traceback (most recent call last):
  File "./layout.py", line 26, in <module>
    soup = BeautifulSoup(data, 'xml')
  File "/home/jiajun/Code/python/layoutcode/lib/python3.4/site-packages/bs4/__init__.py", line 152, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?
```

**Comment by wiiiky** [comment]
依赖BeautifulSoup。不过BeautifulSoup要使用XML解析库。
你这貌似时没有XML解析库的原因，安装lxml试试。
pip3 install lxml
